import { BuilderSectionType, EditableField } from "./types";

export type BuilderRegistryMetaEntry = {
  type: BuilderSectionType;
  displayName: string;
  description: string;
  group: "Hero" | "Products" | "Content" | "Trust/Benefits" | "Promotions" | "Forms";
  icon: string;
  defaultProps: Record<string, unknown>;
  editableSchema: Record<string, EditableField>;
  removable: boolean;
  movable: boolean;
  duplicatable: boolean;
};

export const DEAR_BODY_SECTION_META: Record<BuilderSectionType, BuilderRegistryMetaEntry> = {
  hero_banner: {
    type: "hero_banner",
    displayName: "Hero Banner",
    description: "Top hero section with headline and CTA buttons",
    group: "Hero",
    icon: "🖼️",
    removable: false,
    movable: false,
    duplicatable: false,
    defaultProps: {
      eyebrow: "New Collection",
      title: "Feel good in your skin",
      subtitle: "Body care essentials made simple.",
      primaryButtonText: "Shop Now",
      primaryButtonHref: "/shop",
      secondaryButtonText: "Learn More",
      secondaryButtonHref: "/about",
      layout: "image_right",
      tone: "soft",
    },
    editableSchema: {
      eyebrow: { type: "text", label: "Eyebrow" },
      title: { type: "text", label: "Heading", required: true },
      subtitle: { type: "textarea", label: "Subtitle" },
      imageUrl: { type: "image", label: "Image" },
      primaryButtonText: { type: "text", label: "Primary button text" },
      primaryButtonHref: { type: "url", label: "Primary button link" },
      secondaryButtonText: { type: "text", label: "Secondary button text" },
      secondaryButtonHref: { type: "url", label: "Secondary button link" },
      layout: { type: "select", label: "Layout", options: ["image_right", "image_left", "centered"] },
      tone: { type: "select", label: "Tone", options: ["soft", "clean", "warm", "bold"] },
    },
  },
  featured_products: {
    type: "featured_products",
    displayName: "Featured Products",
    description: "Product grid using existing product cards",
    group: "Products",
    icon: "🛍️",
    removable: true,
    movable: true,
    duplicatable: true,
    defaultProps: {
      title: "Bestselling Products",
      subtitle: "Customer favorites.",
      mode: "latest",
      limit: 8,
      buttonText: "Shop All",
      buttonHref: "/shop",
    },
    editableSchema: {
      title: { type: "text", label: "Title", required: true },
      subtitle: { type: "textarea", label: "Subtitle" },
      mode: { type: "select", label: "Mode", options: ["manual", "latest", "featured"] },
      limit: { type: "number", label: "Item limit", min: 1, max: 12 },
      buttonText: { type: "text", label: "Button text" },
      buttonHref: { type: "url", label: "Button link" },
    },
  },
  image_text: {
    type: "image_text",
    displayName: "Image + Text",
    description: "Split content section with image and copy",
    group: "Content",
    icon: "📝",
    removable: true,
    movable: true,
    duplicatable: true,
    defaultProps: {
      title: "Body care for everyday confidence",
      body: "Made for your routine.",
      buttonText: "Learn More",
      buttonHref: "/about",
      layout: "image_right",
      tone: "clean",
    },
    editableSchema: {
      title: { type: "text", label: "Title", required: true },
      body: { type: "textarea", label: "Body" },
      imageUrl: { type: "image", label: "Image" },
      buttonText: { type: "text", label: "Button text" },
      buttonHref: { type: "url", label: "Button link" },
      layout: { type: "select", label: "Layout", options: ["image_left", "image_right"] },
      tone: { type: "select", label: "Tone", options: ["soft", "clean", "warm", "bold"] },
    },
  },
  benefit_icons: {
    type: "benefit_icons",
    displayName: "Benefit Icons",
    description: "Icon list with key value propositions",
    group: "Trust/Benefits",
    icon: "✅",
    removable: true,
    movable: true,
    duplicatable: true,
    defaultProps: {
      title: "Why shoppers choose Dear Body",
      columns: "4",
      items: [
        { icon: "sparkles", title: "Premium Scents", text: "Layerable fragrances." },
        { icon: "heart", title: "Gentle formulas", text: "Comfort-first body care." },
        { icon: "truck", title: "Fast shipping", text: "Quick local delivery." },
      ],
    },
    editableSchema: {
      title: { type: "text", label: "Title", required: true },
      columns: { type: "select", label: "Columns", options: ["3", "4"] },
      items: { type: "benefit_items", label: "Benefits" },
    },
  },
  promo_banner: {
    type: "promo_banner",
    displayName: "Promo Banner",
    description: "High-impact promotional strip",
    group: "Promotions",
    icon: "🏷️",
    removable: true,
    movable: true,
    duplicatable: true,
    defaultProps: {
      text: "Limited-time promotion",
      buttonText: "Shop Now",
      buttonHref: "/shop",
      tone: "warm",
    },
    editableSchema: {
      text: { type: "text", label: "Text", required: true },
      buttonText: { type: "text", label: "Button text" },
      buttonHref: { type: "url", label: "Button link" },
      tone: { type: "select", label: "Tone", options: ["soft", "clean", "warm", "bold"] },
    },
  },
  rich_text: {
    type: "rich_text",
    displayName: "Rich Text",
    description: "Content block for policies, brand story, and info pages",
    group: "Content",
    icon: "📄",
    removable: true,
    movable: true,
    duplicatable: true,
    defaultProps: {
      title: "About Dear Body",
      content: "Tell your brand story here.",
      alignment: "left",
      maxWidth: "standard",
      tone: "white",
    },
    editableSchema: {
      title: { type: "text", label: "Heading" },
      content: { type: "textarea", label: "Content", required: true },
      alignment: { type: "select", label: "Alignment", options: ["left", "center"] },
      maxWidth: { type: "select", label: "Width", options: ["narrow", "standard", "wide"] },
      tone: { type: "select", label: "Background", options: ["white", "soft", "warm", "muted"] },
    },
  },
  faq_accordion: {
    type: "faq_accordion",
    displayName: "FAQ Accordion",
    description: "Expandable questions and answers",
    group: "Content",
    icon: "❓",
    removable: true,
    movable: true,
    duplicatable: true,
    defaultProps: {
      title: "Frequently Asked Questions",
      subtitle: "Everything you need to know.",
      items: [
        { question: "What is Dear Body?", answer: "Dear Body is a beauty brand specialising in vibrant fragrances and skincare." },
        { question: "How long does delivery take?", answer: "We typically dispatch within 1–2 business days." },
      ],
      tone: "white",
    },
    editableSchema: {
      title: { type: "text", label: "Title" },
      subtitle: { type: "textarea", label: "Subtitle" },
      items: { type: "faq_items", label: "FAQ Items" },
      tone: { type: "select", label: "Background", options: ["white", "soft", "muted"] },
    },
  },
  newsletter_signup: {
    type: "newsletter_signup",
    displayName: "Newsletter Signup",
    description: "Email capture section to grow your subscriber list",
    group: "Forms",
    icon: "✉️",
    removable: true,
    movable: true,
    duplicatable: true,
    defaultProps: {
      title: "Get 10% off your first order",
      subtitle: "Join our newsletter for exclusive deals and beauty tips.",
      placeholder: "Your email address",
      buttonText: "Subscribe",
      disclaimer: "No spam. Unsubscribe anytime.",
      tone: "soft",
    },
    editableSchema: {
      title: { type: "text", label: "Title" },
      subtitle: { type: "textarea", label: "Subtitle" },
      placeholder: { type: "text", label: "Input placeholder" },
      buttonText: { type: "text", label: "Button text" },
      disclaimer: { type: "text", label: "Disclaimer text" },
      tone: { type: "select", label: "Background", options: ["soft", "warm", "bold", "muted"] },
    },
  },
  testimonials: {
    type: "testimonials",
    displayName: "Testimonials",
    description: "Customer reviews and social proof",
    group: "Trust/Benefits",
    icon: "⭐",
    removable: true,
    movable: true,
    duplicatable: true,
    defaultProps: {
      title: "What our customers say",
      items: [
        { quote: "I'm absolutely obsessed with the body sprays. The scent lasts all day!", author: "Sarah M.", role: "Verified Buyer", rating: 5 },
        { quote: "Best skincare I've ever tried. My skin feels amazing.", author: "Lerato K.", role: "Verified Buyer", rating: 5 },
        { quote: "Fast delivery and beautiful packaging. Will definitely order again.", author: "Thandi N.", role: "Verified Buyer", rating: 5 },
      ],
      tone: "white",
    },
    editableSchema: {
      title: { type: "text", label: "Title" },
      items: { type: "testimonial_items", label: "Testimonials" },
      tone: { type: "select", label: "Background", options: ["white", "soft", "muted"] },
    },
  },
  trust_badges: {
    type: "trust_badges",
    displayName: "Trust Badges",
    description: "Security and trust signals for higher conversion",
    group: "Trust/Benefits",
    icon: "🔒",
    removable: true,
    movable: true,
    duplicatable: true,
    defaultProps: {
      title: "Trusted by thousands of customers",
      items: [
        { icon: "lock", label: "Secure Checkout" },
        { icon: "credit_card", label: "Safe Payment" },
        { icon: "money_back", label: "30-Day Returns" },
        { icon: "fast_shipping", label: "Fast Dispatch" },
      ],
      layout: "row",
      tone: "white",
    },
    editableSchema: {
      title: { type: "text", label: "Title" },
      items: { type: "trust_badge_items", label: "Badges" },
      layout: { type: "select", label: "Layout", options: ["row", "grid"] },
      tone: { type: "select", label: "Background", options: ["white", "muted"] },
    },
  },
  countdown_banner: {
    type: "countdown_banner",
    displayName: "Countdown Timer",
    description: "Create urgency with a live countdown promotion",
    group: "Promotions",
    icon: "⏱️",
    removable: true,
    movable: true,
    duplicatable: true,
    defaultProps: {
      headline: "Flash Sale Ends Soon!",
      subtext: "Save 30% on selected products — limited time only.",
      endDate: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000).toISOString(),
      buttonText: "Shop the Sale",
      buttonHref: "/shop",
      tone: "warm",
    },
    editableSchema: {
      headline: { type: "text", label: "Headline" },
      subtext: { type: "textarea", label: "Subtext" },
      endDate: { type: "text", label: "End date (ISO format, e.g. 2026-12-31T23:59:00)" },
      buttonText: { type: "text", label: "Button text" },
      buttonHref: { type: "url", label: "Button link" },
      tone: { type: "select", label: "Tone", options: ["warm", "bold", "soft", "clean"] },
    },
  },
  image_gallery: {
    type: "image_gallery",
    displayName: "Image Gallery",
    description: "Responsive image grid for campaigns and lookbooks",
    group: "Content",
    icon: "🖼️",
    removable: true,
    movable: true,
    duplicatable: true,
    defaultProps: {
      title: "Our Collection",
      images: [],
      columns: "3",
      tone: "white",
    },
    editableSchema: {
      title: { type: "text", label: "Title" },
      images: { type: "gallery_images", label: "Images" },
      columns: { type: "select", label: "Columns", options: ["2", "3", "4"] },
      tone: { type: "select", label: "Background", options: ["white", "muted"] },
    },
  },
  video_banner: {
    type: "video_banner",
    displayName: "Video Banner",
    description: "Autoplay background video with overlay text",
    group: "Content",
    icon: "🎬",
    removable: true,
    movable: true,
    duplicatable: true,
    defaultProps: {
      title: "Experience Dear Body",
      subtitle: "Discover what makes us different.",
      overlayOpacity: "medium",
      buttonText: "Shop Now",
      buttonHref: "/shop",
      tone: "bold",
    },
    editableSchema: {
      title: { type: "text", label: "Title" },
      subtitle: { type: "textarea", label: "Subtitle" },
      videoUrl: { type: "url", label: "Video URL (mp4)" },
      posterUrl: { type: "image", label: "Poster image (fallback)" },
      overlayOpacity: { type: "select", label: "Overlay darkness", options: ["light", "medium", "dark"] },
      buttonText: { type: "text", label: "Button text" },
      buttonHref: { type: "url", label: "Button link" },
    },
  },
  icon_features: {
    type: "icon_features",
    displayName: "Icon Features",
    description: "Feature highlights grid with icons and descriptions",
    group: "Content",
    icon: "💡",
    removable: true,
    movable: true,
    duplicatable: true,
    defaultProps: {
      title: "Why choose Dear Body",
      subtitle: "Everything you love about premium body care.",
      columns: "3",
      items: [
        { icon: "sparkles", title: "Premium Ingredients", description: "Carefully sourced formulas that nourish your skin." },
        { icon: "heart", title: "Made with Love", description: "Every product crafted with care and intention." },
        { icon: "zap", title: "Fast Absorption", description: "Lightweight formulas that absorb quickly." },
      ],
      tone: "white",
    },
    editableSchema: {
      title: { type: "text", label: "Title" },
      subtitle: { type: "textarea", label: "Subtitle" },
      columns: { type: "select", label: "Columns", options: ["2", "3", "4"] },
      items: { type: "feature_items", label: "Features" },
      tone: { type: "select", label: "Background", options: ["white", "soft", "muted"] },
    },
  },
  contact_cta: {
    type: "contact_cta",
    displayName: "Contact CTA",
    description: "Call-to-action section with contact information",
    group: "Forms",
    icon: "📞",
    removable: true,
    movable: true,
    duplicatable: true,
    defaultProps: {
      title: "Get in touch",
      subtitle: "Our team is ready to help you.",
      email: "hello@dearbody.co.za",
      phone: "+27 000 000 0000",
      buttonText: "Send a Message",
      buttonHref: "/contact",
      tone: "dark",
    },
    editableSchema: {
      title: { type: "text", label: "Title" },
      subtitle: { type: "textarea", label: "Subtitle" },
      email: { type: "text", label: "Email address" },
      phone: { type: "text", label: "Phone number" },
      buttonText: { type: "text", label: "Button text" },
      buttonHref: { type: "url", label: "Button link" },
      tone: { type: "select", label: "Background", options: ["dark", "soft", "warm"] },
    },
  },
  spacer: {
    type: "spacer",
    displayName: "Spacer",
    description: "Visual spacing and optional divider line",
    group: "Content",
    icon: "⬜",
    removable: true,
    movable: true,
    duplicatable: true,
    defaultProps: {
      height: "md",
      showDivider: false,
      tone: "white",
    },
    editableSchema: {
      height: { type: "select", label: "Height", options: ["sm", "md", "lg", "xl"] },
      showDivider: { type: "boolean", label: "Show divider line" },
      tone: { type: "select", label: "Background", options: ["white", "muted"] },
    },
  },
};

export const DEAR_BODY_SECTION_META_LIST = Object.values(DEAR_BODY_SECTION_META);
