ALTER TABLE "ShippingMethod"
  ADD COLUMN IF NOT EXISTS "type" TEXT NOT NULL DEFAULT 'DELIVERY',
  ADD COLUMN IF NOT EXISTS "collectionAddress" JSONB;

ALTER TABLE "Order"
  ADD COLUMN IF NOT EXISTS "collectionAddress" JSONB;
